// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: folders.sql

package sqlc

import (
	"context"
)

const approvedExampleCount = `-- name: ApprovedExampleCount :one
SELECT COUNT(*)
FROM routing_examples
WHERE lower(sender) = lower(?1)
	AND lower(recipient) = lower(?2)
	AND recipient_scope = ?3
	AND document_type = ?4
	AND folder = ?5
`

type ApprovedExampleCountParams struct {
	Sender         string `json:"sender"`
	Recipient      string `json:"recipient"`
	RecipientScope string `json:"recipient_scope"`
	DocumentType   string `json:"document_type"`
	Folder         string `json:"folder"`
}

func (q *Queries) ApprovedExampleCount(ctx context.Context, arg ApprovedExampleCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, approvedExampleCount,
		arg.Sender,
		arg.Recipient,
		arg.RecipientScope,
		arg.DocumentType,
		arg.Folder,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRoutingExamples = `-- name: CountRoutingExamples :one
SELECT COUNT(*) FROM routing_examples
`

func (q *Queries) CountRoutingExamples(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRoutingExamples)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteStaleArchiveFolders = `-- name: DeleteStaleArchiveFolders :exec
DELETE FROM folders
WHERE source = 'archive'
  AND last_seen <> ?
  AND approved_count = 0
  AND NOT EXISTS (
    SELECT 1 FROM routing_examples WHERE routing_examples.folder = folders.path
  )
`

func (q *Queries) DeleteStaleArchiveFolders(ctx context.Context, lastSeen string) error {
	_, err := q.db.ExecContext(ctx, deleteStaleArchiveFolders, lastSeen)
	return err
}

const deleteUnapprovedConfigFolders = `-- name: DeleteUnapprovedConfigFolders :exec
DELETE FROM folders
WHERE source = 'config'
  AND approved_count = 0
  AND NOT EXISTS (
    SELECT 1 FROM routing_examples WHERE routing_examples.folder = folders.path
  )
`

func (q *Queries) DeleteUnapprovedConfigFolders(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteUnapprovedConfigFolders)
	return err
}

const getFolderApprovedCount = `-- name: GetFolderApprovedCount :one
SELECT approved_count
FROM folders
WHERE path = ?
`

func (q *Queries) GetFolderApprovedCount(ctx context.Context, path string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getFolderApprovedCount, path)
	var approved_count int64
	err := row.Scan(&approved_count)
	return approved_count, err
}

const incrementFolderApproval = `-- name: IncrementFolderApproval :exec
UPDATE folders
SET approved_count = approved_count + 1, last_seen = ?
WHERE path = ?
`

type IncrementFolderApprovalParams struct {
	LastSeen string `json:"last_seen"`
	Path     string `json:"path"`
}

func (q *Queries) IncrementFolderApproval(ctx context.Context, arg IncrementFolderApprovalParams) error {
	_, err := q.db.ExecContext(ctx, incrementFolderApproval, arg.LastSeen, arg.Path)
	return err
}

const insertRoutingExample = `-- name: InsertRoutingExample :exec
INSERT INTO routing_examples (
	created_at, source_job_id, sender, recipient, recipient_scope, document_type, folder, filename, weight
) VALUES (
	?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type InsertRoutingExampleParams struct {
	CreatedAt      string  `json:"created_at"`
	SourceJobID    string  `json:"source_job_id"`
	Sender         string  `json:"sender"`
	Recipient      string  `json:"recipient"`
	RecipientScope string  `json:"recipient_scope"`
	DocumentType   string  `json:"document_type"`
	Folder         string  `json:"folder"`
	Filename       string  `json:"filename"`
	Weight         float64 `json:"weight"`
}

func (q *Queries) InsertRoutingExample(ctx context.Context, arg InsertRoutingExampleParams) error {
	_, err := q.db.ExecContext(ctx, insertRoutingExample,
		arg.CreatedAt,
		arg.SourceJobID,
		arg.Sender,
		arg.Recipient,
		arg.RecipientScope,
		arg.DocumentType,
		arg.Folder,
		arg.Filename,
		arg.Weight,
	)
	return err
}

const listApprovedFolders = `-- name: ListApprovedFolders :many
SELECT path
FROM folders
WHERE approved_count > 0
ORDER BY path
`

func (q *Queries) ListApprovedFolders(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listApprovedFolders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFolders = `-- name: ListFolders :many
SELECT path
FROM folders
ORDER BY path
`

func (q *Queries) ListFolders(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listFolders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutingExamples = `-- name: ListRoutingExamples :many
SELECT sender, recipient, recipient_scope, document_type, folder, MAX(filename) AS filename, COUNT(*) AS approvals
FROM routing_examples
GROUP BY sender, recipient, recipient_scope, document_type, folder
ORDER BY MAX(id) DESC
LIMIT 500
`

type ListRoutingExamplesRow struct {
	Sender         string      `json:"sender"`
	Recipient      string      `json:"recipient"`
	RecipientScope string      `json:"recipient_scope"`
	DocumentType   string      `json:"document_type"`
	Folder         string      `json:"folder"`
	Filename       interface{} `json:"filename"`
	Approvals      int64       `json:"approvals"`
}

func (q *Queries) ListRoutingExamples(ctx context.Context) ([]ListRoutingExamplesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRoutingExamples)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoutingExamplesRow{}
	for rows.Next() {
		var i ListRoutingExamplesRow
		if err := rows.Scan(
			&i.Sender,
			&i.Recipient,
			&i.RecipientScope,
			&i.DocumentType,
			&i.Folder,
			&i.Filename,
			&i.Approvals,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFolder = `-- name: UpsertFolder :exec
INSERT INTO folders (path, source, first_seen, last_seen)
VALUES (?, ?, ?, ?)
ON CONFLICT(path) DO UPDATE SET last_seen = excluded.last_seen
`

type UpsertFolderParams struct {
	Path      string `json:"path"`
	Source    string `json:"source"`
	FirstSeen string `json:"first_seen"`
	LastSeen  string `json:"last_seen"`
}

func (q *Queries) UpsertFolder(ctx context.Context, arg UpsertFolderParams) error {
	_, err := q.db.ExecContext(ctx, upsertFolder,
		arg.Path,
		arg.Source,
		arg.FirstSeen,
		arg.LastSeen,
	)
	return err
}
