// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package sqlc

import (
	"context"
)

const addEvent = `-- name: AddEvent :exec
INSERT INTO events (job_id, created_at, level, message)
VALUES (?, ?, ?, ?)
`

type AddEventParams struct {
	JobID     string `json:"job_id"`
	CreatedAt string `json:"created_at"`
	Level     string `json:"level"`
	Message   string `json:"message"`
}

func (q *Queries) AddEvent(ctx context.Context, arg AddEventParams) error {
	_, err := q.db.ExecContext(ctx, addEvent,
		arg.JobID,
		arg.CreatedAt,
		arg.Level,
		arg.Message,
	)
	return err
}

const createJob = `-- name: CreateJob :exec
INSERT INTO jobs (
	id, source_filename, current_path, scan_timestamp, updated_at, status
) VALUES (
	?, ?, ?, ?, ?, ?
)
`

type CreateJobParams struct {
	ID             string `json:"id"`
	SourceFilename string `json:"source_filename"`
	CurrentPath    string `json:"current_path"`
	ScanTimestamp  string `json:"scan_timestamp"`
	UpdatedAt      string `json:"updated_at"`
	Status         string `json:"status"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) error {
	_, err := q.db.ExecContext(ctx, createJob,
		arg.ID,
		arg.SourceFilename,
		arg.CurrentPath,
		arg.ScanTimestamp,
		arg.UpdatedAt,
		arg.Status,
	)
	return err
}

const findDuplicateByHash = `-- name: FindDuplicateByHash :one
SELECT id, source_filename, raw_path, current_path, final_path, text_path, file_hash, text_hash, scan_timestamp, updated_at, status, page_count, summary, classification_json, confidence, physical_original_action, error, duplicate_of, manual_override, input_kind, text_source
FROM jobs
WHERE file_hash = ? AND id != ?
ORDER BY scan_timestamp ASC
LIMIT 1
`

type FindDuplicateByHashParams struct {
	FileHash string `json:"file_hash"`
	ID       string `json:"id"`
}

func (q *Queries) FindDuplicateByHash(ctx context.Context, arg FindDuplicateByHashParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, findDuplicateByHash, arg.FileHash, arg.ID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.SourceFilename,
		&i.RawPath,
		&i.CurrentPath,
		&i.FinalPath,
		&i.TextPath,
		&i.FileHash,
		&i.TextHash,
		&i.ScanTimestamp,
		&i.UpdatedAt,
		&i.Status,
		&i.PageCount,
		&i.Summary,
		&i.ClassificationJson,
		&i.Confidence,
		&i.PhysicalOriginalAction,
		&i.Error,
		&i.DuplicateOf,
		&i.ManualOverride,
		&i.InputKind,
		&i.TextSource,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, source_filename, raw_path, current_path, final_path, text_path, file_hash, text_hash, scan_timestamp, updated_at, status, page_count, summary, classification_json, confidence, physical_original_action, error, duplicate_of, manual_override, input_kind, text_source
FROM jobs
WHERE id = ?
`

func (q *Queries) GetJob(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.SourceFilename,
		&i.RawPath,
		&i.CurrentPath,
		&i.FinalPath,
		&i.TextPath,
		&i.FileHash,
		&i.TextHash,
		&i.ScanTimestamp,
		&i.UpdatedAt,
		&i.Status,
		&i.PageCount,
		&i.Summary,
		&i.ClassificationJson,
		&i.Confidence,
		&i.PhysicalOriginalAction,
		&i.Error,
		&i.DuplicateOf,
		&i.ManualOverride,
		&i.InputKind,
		&i.TextSource,
	)
	return i, err
}

const listAllJobs = `-- name: ListAllJobs :many
SELECT id, source_filename, raw_path, current_path, final_path, text_path, file_hash, text_hash, scan_timestamp, updated_at, status, page_count, summary, classification_json, confidence, physical_original_action, error, duplicate_of, manual_override, input_kind, text_source
FROM jobs
ORDER BY updated_at DESC
`

func (q *Queries) ListAllJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listAllJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.SourceFilename,
			&i.RawPath,
			&i.CurrentPath,
			&i.FinalPath,
			&i.TextPath,
			&i.FileHash,
			&i.TextHash,
			&i.ScanTimestamp,
			&i.UpdatedAt,
			&i.Status,
			&i.PageCount,
			&i.Summary,
			&i.ClassificationJson,
			&i.Confidence,
			&i.PhysicalOriginalAction,
			&i.Error,
			&i.DuplicateOf,
			&i.ManualOverride,
			&i.InputKind,
			&i.TextSource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentJobs = `-- name: ListRecentJobs :many
SELECT id, source_filename, raw_path, current_path, final_path, text_path, file_hash, text_hash, scan_timestamp, updated_at, status, page_count, summary, classification_json, confidence, physical_original_action, error, duplicate_of, manual_override, input_kind, text_source
FROM jobs
ORDER BY updated_at DESC
LIMIT ?
`

func (q *Queries) ListRecentJobs(ctx context.Context, limit int64) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listRecentJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.SourceFilename,
			&i.RawPath,
			&i.CurrentPath,
			&i.FinalPath,
			&i.TextPath,
			&i.FileHash,
			&i.TextHash,
			&i.ScanTimestamp,
			&i.UpdatedAt,
			&i.Status,
			&i.PageCount,
			&i.Summary,
			&i.ClassificationJson,
			&i.Confidence,
			&i.PhysicalOriginalAction,
			&i.Error,
			&i.DuplicateOf,
			&i.ManualOverride,
			&i.InputKind,
			&i.TextSource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewJobs = `-- name: ListReviewJobs :many
SELECT id, source_filename, raw_path, current_path, final_path, text_path, file_hash, text_hash, scan_timestamp, updated_at, status, page_count, summary, classification_json, confidence, physical_original_action, error, duplicate_of, manual_override, input_kind, text_source
FROM jobs
WHERE status IN ('needs_review', 'failed', 'rejected')
ORDER BY updated_at DESC
LIMIT ?
`

func (q *Queries) ListReviewJobs(ctx context.Context, limit int64) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listReviewJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.SourceFilename,
			&i.RawPath,
			&i.CurrentPath,
			&i.FinalPath,
			&i.TextPath,
			&i.FileHash,
			&i.TextHash,
			&i.ScanTimestamp,
			&i.UpdatedAt,
			&i.Status,
			&i.PageCount,
			&i.Summary,
			&i.ClassificationJson,
			&i.Confidence,
			&i.PhysicalOriginalAction,
			&i.Error,
			&i.DuplicateOf,
			&i.ManualOverride,
			&i.InputKind,
			&i.TextSource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setArchived = `-- name: SetArchived :exec
UPDATE jobs
SET current_path = ?, final_path = ?, status = ?, updated_at = ?
WHERE id = ?
`

type SetArchivedParams struct {
	CurrentPath string `json:"current_path"`
	FinalPath   string `json:"final_path"`
	Status      string `json:"status"`
	UpdatedAt   string `json:"updated_at"`
	ID          string `json:"id"`
}

func (q *Queries) SetArchived(ctx context.Context, arg SetArchivedParams) error {
	_, err := q.db.ExecContext(ctx, setArchived,
		arg.CurrentPath,
		arg.FinalPath,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const setClassified = `-- name: SetClassified :exec
UPDATE jobs
SET classification_json = ?, confidence = ?, summary = ?, physical_original_action = ?, status = ?, updated_at = ?
WHERE id = ?
`

type SetClassifiedParams struct {
	ClassificationJson     string  `json:"classification_json"`
	Confidence             float64 `json:"confidence"`
	Summary                string  `json:"summary"`
	PhysicalOriginalAction string  `json:"physical_original_action"`
	Status                 string  `json:"status"`
	UpdatedAt              string  `json:"updated_at"`
	ID                     string  `json:"id"`
}

func (q *Queries) SetClassified(ctx context.Context, arg SetClassifiedParams) error {
	_, err := q.db.ExecContext(ctx, setClassified,
		arg.ClassificationJson,
		arg.Confidence,
		arg.Summary,
		arg.PhysicalOriginalAction,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const setCurrentStatus = `-- name: SetCurrentStatus :exec
UPDATE jobs
SET current_path = ?, status = ?, updated_at = ?
WHERE id = ?
`

type SetCurrentStatusParams struct {
	CurrentPath string `json:"current_path"`
	Status      string `json:"status"`
	UpdatedAt   string `json:"updated_at"`
	ID          string `json:"id"`
}

func (q *Queries) SetCurrentStatus(ctx context.Context, arg SetCurrentStatusParams) error {
	_, err := q.db.ExecContext(ctx, setCurrentStatus,
		arg.CurrentPath,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const setDuplicate = `-- name: SetDuplicate :exec
UPDATE jobs
SET current_path = ?, status = ?, duplicate_of = ?, physical_original_action = ?, updated_at = ?
WHERE id = ?
`

type SetDuplicateParams struct {
	CurrentPath            string `json:"current_path"`
	Status                 string `json:"status"`
	DuplicateOf            string `json:"duplicate_of"`
	PhysicalOriginalAction string `json:"physical_original_action"`
	UpdatedAt              string `json:"updated_at"`
	ID                     string `json:"id"`
}

func (q *Queries) SetDuplicate(ctx context.Context, arg SetDuplicateParams) error {
	_, err := q.db.ExecContext(ctx, setDuplicate,
		arg.CurrentPath,
		arg.Status,
		arg.DuplicateOf,
		arg.PhysicalOriginalAction,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const setFailed = `-- name: SetFailed :exec
UPDATE jobs
SET status = ?, error = ?, physical_original_action = ?, updated_at = ?
WHERE id = ?
`

type SetFailedParams struct {
	Status                 string `json:"status"`
	Error                  string `json:"error"`
	PhysicalOriginalAction string `json:"physical_original_action"`
	UpdatedAt              string `json:"updated_at"`
	ID                     string `json:"id"`
}

func (q *Queries) SetFailed(ctx context.Context, arg SetFailedParams) error {
	_, err := q.db.ExecContext(ctx, setFailed,
		arg.Status,
		arg.Error,
		arg.PhysicalOriginalAction,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const setManualArchived = `-- name: SetManualArchived :exec
UPDATE jobs
SET current_path = ?, final_path = ?, status = ?, physical_original_action = ?, manual_override = ?, updated_at = ?
WHERE id = ?
`

type SetManualArchivedParams struct {
	CurrentPath            string `json:"current_path"`
	FinalPath              string `json:"final_path"`
	Status                 string `json:"status"`
	PhysicalOriginalAction string `json:"physical_original_action"`
	ManualOverride         int64  `json:"manual_override"`
	UpdatedAt              string `json:"updated_at"`
	ID                     string `json:"id"`
}

func (q *Queries) SetManualArchived(ctx context.Context, arg SetManualArchivedParams) error {
	_, err := q.db.ExecContext(ctx, setManualArchived,
		arg.CurrentPath,
		arg.FinalPath,
		arg.Status,
		arg.PhysicalOriginalAction,
		arg.ManualOverride,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const setNeedsReview = `-- name: SetNeedsReview :exec
UPDATE jobs
SET current_path = ?, status = ?, updated_at = ?
WHERE id = ?
`

type SetNeedsReviewParams struct {
	CurrentPath string `json:"current_path"`
	Status      string `json:"status"`
	UpdatedAt   string `json:"updated_at"`
	ID          string `json:"id"`
}

func (q *Queries) SetNeedsReview(ctx context.Context, arg SetNeedsReviewParams) error {
	_, err := q.db.ExecContext(ctx, setNeedsReview,
		arg.CurrentPath,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const setOCRComplete = `-- name: SetOCRComplete :exec
UPDATE jobs
SET current_path = ?, text_path = ?, text_hash = ?, page_count = ?, input_kind = ?, text_source = ?, status = ?, updated_at = ?
WHERE id = ?
`

type SetOCRCompleteParams struct {
	CurrentPath string `json:"current_path"`
	TextPath    string `json:"text_path"`
	TextHash    string `json:"text_hash"`
	PageCount   int64  `json:"page_count"`
	InputKind   string `json:"input_kind"`
	TextSource  string `json:"text_source"`
	Status      string `json:"status"`
	UpdatedAt   string `json:"updated_at"`
	ID          string `json:"id"`
}

func (q *Queries) SetOCRComplete(ctx context.Context, arg SetOCRCompleteParams) error {
	_, err := q.db.ExecContext(ctx, setOCRComplete,
		arg.CurrentPath,
		arg.TextPath,
		arg.TextHash,
		arg.PageCount,
		arg.InputKind,
		arg.TextSource,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const setRawCopy = `-- name: SetRawCopy :exec
UPDATE jobs
SET raw_path = ?, file_hash = ?, status = ?, updated_at = ?
WHERE id = ?
`

type SetRawCopyParams struct {
	RawPath   string `json:"raw_path"`
	FileHash  string `json:"file_hash"`
	Status    string `json:"status"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) SetRawCopy(ctx context.Context, arg SetRawCopyParams) error {
	_, err := q.db.ExecContext(ctx, setRawCopy,
		arg.RawPath,
		arg.FileHash,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const setRejected = `-- name: SetRejected :exec
UPDATE jobs
SET current_path = ?, status = ?, physical_original_action = ?, manual_override = ?, updated_at = ?
WHERE id = ?
`

type SetRejectedParams struct {
	CurrentPath            string `json:"current_path"`
	Status                 string `json:"status"`
	PhysicalOriginalAction string `json:"physical_original_action"`
	ManualOverride         int64  `json:"manual_override"`
	UpdatedAt              string `json:"updated_at"`
	ID                     string `json:"id"`
}

func (q *Queries) SetRejected(ctx context.Context, arg SetRejectedParams) error {
	_, err := q.db.ExecContext(ctx, setRejected,
		arg.CurrentPath,
		arg.Status,
		arg.PhysicalOriginalAction,
		arg.ManualOverride,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
