// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type DocumentBlock struct {
	JobID              string  `json:"job_id"`
	SourceHash         string  `json:"source_hash"`
	Version            int64   `json:"version"`
	DistanceMultiplier float64 `json:"distance_multiplier"`
	BlocksJson         string  `json:"blocks_json"`
	UpdatedAt          string  `json:"updated_at"`
	UnifiedJson        string  `json:"unified_json"`
}

type DocumentEmbedding struct {
	JobID       string `json:"job_id"`
	ContentHash string `json:"content_hash"`
	ModelKey    string `json:"model_key"`
	Dimensions  int64  `json:"dimensions"`
	IndexedAt   string `json:"indexed_at"`
	Centroid    []byte `json:"centroid"`
}

type DocumentPage struct {
	JobID          string `json:"job_id"`
	Page           int64  `json:"page"`
	SuggestedBlank int64  `json:"suggested_blank"`
	Excluded       int64  `json:"excluded"`
	Reason         string `json:"reason"`
}

type EmbeddingChunk struct {
	JobID          string        `json:"job_id"`
	Ordinal        int64         `json:"ordinal"`
	Excerpt        string        `json:"excerpt"`
	Vector         []byte        `json:"vector"`
	BlockID        sql.NullInt64 `json:"block_id"`
	SourceBlockIds string        `json:"source_block_ids"`
}

type Event struct {
	ID        int64  `json:"id"`
	JobID     string `json:"job_id"`
	CreatedAt string `json:"created_at"`
	Level     string `json:"level"`
	Message   string `json:"message"`
}

type Folder struct {
	Path          string `json:"path"`
	Source        string `json:"source"`
	FirstSeen     string `json:"first_seen"`
	LastSeen      string `json:"last_seen"`
	ApprovedCount int64  `json:"approved_count"`
}

type Job struct {
	ID                     string  `json:"id"`
	SourceFilename         string  `json:"source_filename"`
	RawPath                string  `json:"raw_path"`
	CurrentPath            string  `json:"current_path"`
	FinalPath              string  `json:"final_path"`
	TextPath               string  `json:"text_path"`
	FileHash               string  `json:"file_hash"`
	TextHash               string  `json:"text_hash"`
	ScanTimestamp          string  `json:"scan_timestamp"`
	UpdatedAt              string  `json:"updated_at"`
	Status                 string  `json:"status"`
	PageCount              int64   `json:"page_count"`
	Summary                string  `json:"summary"`
	ClassificationJson     string  `json:"classification_json"`
	Confidence             float64 `json:"confidence"`
	PhysicalOriginalAction string  `json:"physical_original_action"`
	Error                  string  `json:"error"`
	DuplicateOf            string  `json:"duplicate_of"`
	ManualOverride         int64   `json:"manual_override"`
	InputKind              string  `json:"input_kind"`
	TextSource             string  `json:"text_source"`
}

type RecipientAddress struct {
	Address string `json:"address"`
}

type RecipientProfile struct {
	ID           int64  `json:"id"`
	Name         string `json:"name"`
	Scope        string `json:"scope"`
	Aliases      string `json:"aliases"`
	FolderPrefix string `json:"folder_prefix"`
	Addresses    string `json:"addresses"`
}

type RoutingExample struct {
	ID             int64   `json:"id"`
	CreatedAt      string  `json:"created_at"`
	SourceJobID    string  `json:"source_job_id"`
	Sender         string  `json:"sender"`
	Folder         string  `json:"folder"`
	Filename       string  `json:"filename"`
	Weight         float64 `json:"weight"`
	Recipient      string  `json:"recipient"`
	RecipientScope string  `json:"recipient_scope"`
}
