// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

type Event struct {
	ID        int64  `json:"id"`
	JobID     string `json:"job_id"`
	CreatedAt string `json:"created_at"`
	Level     string `json:"level"`
	Message   string `json:"message"`
}

type Folder struct {
	Path          string `json:"path"`
	Source        string `json:"source"`
	FirstSeen     string `json:"first_seen"`
	LastSeen      string `json:"last_seen"`
	ApprovedCount int64  `json:"approved_count"`
}

type Job struct {
	ID                     string  `json:"id"`
	SourceFilename         string  `json:"source_filename"`
	RawPath                string  `json:"raw_path"`
	CurrentPath            string  `json:"current_path"`
	FinalPath              string  `json:"final_path"`
	TextPath               string  `json:"text_path"`
	FileHash               string  `json:"file_hash"`
	TextHash               string  `json:"text_hash"`
	ScanTimestamp          string  `json:"scan_timestamp"`
	UpdatedAt              string  `json:"updated_at"`
	Status                 string  `json:"status"`
	PageCount              int64   `json:"page_count"`
	Summary                string  `json:"summary"`
	ClassificationJson     string  `json:"classification_json"`
	Confidence             float64 `json:"confidence"`
	PhysicalOriginalAction string  `json:"physical_original_action"`
	Error                  string  `json:"error"`
	DuplicateOf            string  `json:"duplicate_of"`
	ManualOverride         int64   `json:"manual_override"`
	InputKind              string  `json:"input_kind"`
	TextSource             string  `json:"text_source"`
}

type RoutingExample struct {
	ID           int64   `json:"id"`
	CreatedAt    string  `json:"created_at"`
	SourceJobID  string  `json:"source_job_id"`
	Sender       string  `json:"sender"`
	DocumentType string  `json:"document_type"`
	Folder       string  `json:"folder"`
	Filename     string  `json:"filename"`
	Weight       float64 `json:"weight"`
	Recipient    string  `json:"recipient"`
}
